apiVersion: v1
kind: Service
metadata:
  name: DEPLOYMENT-NAME-service
  namespace: default
spec:
  ports:
    - name: DEPLOYMENT-NAME-9090
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: DEPLOYMENT-NAME-9095
      port: 9095
      protocol: TCP
      targetPort: 9095
  selector:
    app: DEPLOYMENT-NAME
    tier: microservices
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
